#!/usr/bin/env python3

import sys
import time
import math

def factorize(n):
	'''Takes a number as input.
    	Args:
        	num: input integer.
        	Return: A tuple of two factors if the number is not a prime.
                	None if the number is prime.
    	'''
	for i in range(2, int(math.sqrt(n))+1):
        if n % i == 0:
            return (i, n//i)
    return None

if __name__ == "__main__":
	'''Reads the input file.'''
	if len(sys.argv) != 2:
		print("Usage: factors <file>")
    		sys.exit(1)

	input_file = sys.argv[1]

	try:
    		with open(input_file, 'r') as file:
			start_time = time.time()
        		for line in file:
            			n = int(line.strip())
            			p, q = factorize(n)
            			print("{}={}*{}".format(n, p, q))
				if time.time() - start_time > 5:
            				print("Time limit exceeded")
            				sys.exit(1)
	except IOError:
    		print("Error: Could not read file", input_file)
    		sys.exit(1)
